name: 'instructor_workout_dbt'
version: '1.0.0'
config-version: 2

profile: 'instructor_workout_dbt'

models:
  instructor_workout_dbt:
    +persist_docs:
      relation: true
      columns: true

    bronze:
      +schema: bronze

    silver:
      +schema: silver

    gold:
      +schema: gold
