instructor_workout_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: instructor_workout.duckdb
      schema: main
      threads: 4
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "sa-east-1"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
        s3_session_token: ""
        s3_use_ssl: true
