version: 2

models:
  - name: silver_users
    description: "Camada Silver de usuários gerada pelo pipeline, já limpa e normalizada."
    columns:
      - name: user_id
        description: "Identificador único do usuário."
        tests:
          - not_null
      - name: full_name
        description: "Nome completo do usuário."
      - name: gender
        description: "Gênero informado."
      - name: birth_date
        description: "Data de nascimento."
      - name: goal
        description: "Objetivo principal (ex: hipertrofia, emagrecimento)."

  - name: silver_exercises
    description: "Camada Silver de exercícios, derivada do dataset de Kaggle."
    columns:
      - name: exercise_id
        description: "Identificador único do exercício."
      - name: exercise_name
        description: "Nome do exercício."
      - name: primary_muscle
        description: "Principal músculo trabalhado."

  - name: silver_workouts
    description: "Workouts realistas sintetizados na camada Silver."
    columns:
      - name: workout_id
        description: "Identificador único do treino."
      - name: user_id
        description: "Referência ao usuário executor do treino."
      - name: workout_datetime
        description: "Data e hora do treino."
      - name: workout_date
        description: "Data (dia) do treino."
      - name: exercise_id
        description: "Exercício realizado."
      - name: sets
        description: "Número de séries."
      - name: reps
        description: "Número de repetições."
      - name: weight
        description: "Carga utilizada."
      - name: volume
        description: "Métrica de volume (ex: sets * reps * weight)."

  - name: dim_users
    description: "Dimensão de usuários, com o último snapshot de perfil."
    columns:
      - name: user_id
        description: "Chave primária da dimensão de usuários."
        tests:
          - not_null
          - unique
      - name: full_name
        description: "Nome completo."
      - name: goal
        description: "Objetivo de treino do usuário."

  - name: dim_exercises
    description: "Dimensão de exercícios para análises e recomendações."
    columns:
      - name: exercise_id
        description: "Chave primária de exercício."
        tests:
          - not_null
          - unique
      - name: exercise_name
        description: "Nome do exercício."
      - name: primary_muscle
        description: "Principal músculo trabalhado."

  - name: fact_workouts
    description: "Fato de treinos com medidas de desempenho."
    columns:
      - name: workout_id
        description: "Chave do treino."
      - name: user_id
        description: "Chave para dim_users."
      - name: exercise_id
        description: "Chave para dim_exercises."
      - name: volume
        description: "Volume total do exercício na sessão."

  - name: gold_workouts_enriched
    description: "Tabela Gold combinando usuários, exercícios e treinos, pronta para dashboards e IA."
    columns:
      - name: user_id
        description: "Identificador do usuário."
      - name: full_name
        description: "Nome do usuário."
      - name: primary_muscle
        description: "Principal músculo atingido no exercício."
      - name: sets
        description: "Séries executadas no exercício."
